// tools/gen-ssr.mjs — regenerates demo/index.html.
//
// Runs the framework's own SSR module (phos80/ssr.js) over the demo's
// welcome doc and writes a host page containing the prerendered skeleton —
// exactly what a real server would emit. Run after changing demo content:
//
//   node tools/gen-ssr.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { renderScreen, renderText } from '../phos80/ssr.js';
import { WELCOME_DOC } from '../demo/content.js';

const COLS = 80;
const screenHTML = renderScreen(WELCOME_DOC, { cols: COLS });

// Plain-text preview so layout breakage is visible in the diff/terminal:
console.error(renderText(WELCOME_DOC, { cols: COLS }));
console.error(`--- prerendered at ${COLS} cols ---`);

const page = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, interactive-widget=resizes-content">
  <title>phos80 — amber phosphor terminal</title>
  <meta name="description" content="A modern website that thinks it is 1983: an amber phosphor terminal interface with character-drawn frames, responsive reflow, and a command line.">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect width='16' height='16' fill='%230d0805'/%3E%3Ctext x='2' y='12' font-family='monospace' font-size='11' fill='%23ffb000'%3E%26gt;_%3C/text%3E%3C/svg%3E">
  <link rel="stylesheet" href="../phos80/phos80.css">
  <style>
    /* Host-page concerns only — the component styles itself. */
    html, body { height: 100%; }
    body { margin: 0; background: #050302; }
    #terminal { height: 100dvh; }
  </style>
</head>
<body>
  <!-- Server-prerendered skeleton (generated by tools/gen-ssr.mjs — do not
       hand-edit). Fully readable without JS; demo.js adopts and re-renders
       it at the measured width on load. -->
  <div id="terminal" class="p80">
    <div class="p80-crt" data-p80="crt">
      <div class="p80-term" data-p80="term">
        <div class="p80-header" data-p80="header"></div>
        <main class="p80-screen" data-p80="screen">
${screenHTML}
        </main>
        <form class="p80-prompt" data-p80="prompt" autocomplete="off">
          <span class="p80-ps1" data-p80="ps1" aria-hidden="true">&gt;</span>
          <input class="p80-cmd" data-p80="cmd" type="text" spellcheck="false"
                 autocapitalize="off" placeholder="type help" aria-label="command input">
        </form>
      </div>
      <div class="p80-overlay" data-p80="overlay" aria-hidden="true"></div>
      <div class="p80-colsbadge" data-p80="colsbadge" aria-hidden="true">${COLS} COLS</div>
      <div class="p80-sronly" data-p80="srlive" role="status" aria-live="polite"></div>
    </div>
  </div>
  <script type="module" src="demo.js"></script>
</body>
</html>
`;

const out = fileURLToPath(new URL('../demo/index.html', import.meta.url));
writeFileSync(out, page);
console.error(`wrote ${out}`);
